version: "3.4"

services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - "80:80"
      - "443:443"
      - "50000:50000"
      - "50001:50001" # New
    networks:
      - proxy
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
    environment:
      LISTENER_ADDRESS: "swarm-listener"
      SERVICE_IGNORE: "true"
      MODE: "swarm"
      BIND_PORTS: 50000

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DF_NOTIFY_CREATE_SERVICE_URL: "http://proxy:8080/v1/docker-flow-proxy/reconfigure"
      DF_NOTIFY_REMOVE_SERVICE_URL: "http://proxy:8080/v1/docker-flow-proxy/remove"
      SERVICE_IGNORE: "true"
    deploy:
#      replicas: 3 # NOTE: There's no need for three replicas
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2

networks:
  proxy:
    external: true