version: "3.2"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:${TAG:-latest}
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEBUG=true
      - EXTRA_FRONTEND=acl is_root path -i /,acl missing_slash path_reg ^/*/[^/]*$$,http-request redirect code 301 prefix / append-slash if missing_slash !is_root
      - DFP_SERVICE_1_ACL_NAME=shared-cloud-one.mydomain.io
      - DFP_SERVICE_1_SERVICE_DOMAIN=shared-cloud-one.mydomain.io
      - DFP_SERVICE_1_SERVICE_NAME=components2-new.mydomain.io
      - DFP_SERVICE_1_SERVICE_PATH=/components
      - DFP_SERVICE_1_OUTBOUND_HOSTNAME=components-.mydomain.io
      - DFP_SERVICE_1_PORT=443
      - DFP_SERVICE_1_REQ_PATH_SEARCH=/components/
      - DFP_SERVICE_1_REQ_PATH_REPLACE=/
      - DFP_SERVICE_1_HTTPS_ONLY=true
      - DFP_SERVICE_1_SSL_VERIFY_NONE=true
      - DFP_SERVICE_1_ADD_REQ_HEADER=realm shared-cloud-one
      - DFP_SERVICE_1_SET_REQ_HEADER=Host components-new.mydomain.io

      - DFP_SERVICE_2_ACL_NAME=shared-cloud-two.mydomain.io
      - DFP_SERVICE_2_SERVICE_DOMAIN=shared-cloud-two.mydomain.io
      - DFP_SERVICE_2_SERVICE_NAME=components-new.mydomain.io
      - DFP_SERVICE_2_SERVICE_PATH=/components
      - DFP_SERVICE_2_OUTBOUND_HOSTNAME=components-new.mydomain.io
      - DFP_SERVICE_2_PORT=443
      - DFP_SERVICE_2_REQ_PATH_SEARCH=/components/
      - DFP_SERVICE_2_REQ_PATH_REPLACE=/
      - DFP_SERVICE_2_HTTPS_ONLY=true
      - DFP_SERVICE_2_SSL_VERIFY_NONE=true
      - DFP_SERVICE_2_ADD_REQ_HEADER=realm shared-cloud-one
      - DFP_SERVICE_2_SET_REQ_HEADER=Host components-new.mydomain.io

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
